folio-org/mod-organizations-storage

descriptors/ModuleDescriptor-template.json, ramls/address.raml, ramls/category.raml, ramls/contact.raml, ramls/email.raml, ramls/interface.raml, ramls/organization.raml, ramls/phone_number.raml, ramls/url.raml, src/main/java/org/folio/rest/impl/AddressesAPI.java, src/main/java/org/folio/rest/impl/CategoriesAPI.java, src/main/java/org/folio/rest/impl/ContactsAPI.java, src/main/java/org/folio/rest/impl/EmailsAPI.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/rest/impl/PhoneNumbersAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/impl/UrlsAPI.java, src/test/java/org/folio/rest/utils/TestEntities.java
Update the endpoints to comply with [Acquisitions API Listing](https://docs.google.com/spreadsheets/d/1se-a2owRfHLG5eaAZglx4vLvRClCKGp2wZCfD39ZJRY/view#gid=427229289)
[FOLIO-1957 comments](https://issues.folio.org/browse/FOLIO-1957?focusedCommentId=48961&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-48961) 
- changed endpoints prefix in ramls and moduleDescriptor from `/organization-storage` to `/organizations-storage`
- updated API implementations in line with endpoint changes
- What other …
=> MODORGS-4 change endpoints to plural

src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/interfaces/acso_interface.json, src/main/resources/data/interfaces/alexs_interface.json, src/main/resources/data/interfaces/amaz_interface.json, src/main/resources/data/interfaces/gobi_interface.json, src/main/resources/data/interfaces/harra_interface.json, src/main/resources/data/interfaces/mgnp_interface.json, src/main/resources/data/interfaces/naxo_interface.json, src/main/resources/data/interfaces/srebsco_interface.json, src/main/resources/data/interfaces/tafg_interface.json, src/main/resources/data/interfaces/usgs_interface.json, src/main/resources/data/organizations/acso.json, src/main/resources/data/organizations/alexs.json, src/main/resources/data/organizations/amaz.json, src/main/resources/data/organizations/gobi.json, src/main/resources/data/organizations/harra.json, src/main/resources/data/organizations/mgnp.json, src/main/resources/data/organizations/naxo.json, src/main/resources/data/organizations/sjean.json, src/main/resources/data/organizations/srebsco.json, src/main/resources/data/organizations/tafg.json, src/main/resources/data/organizations/usgs.json, src/main/resources/data/organizations/zroco.json, src/main/resources/data/organizations/zsusan.json, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORGS-20](https://issues.folio.org/browse/MODORGS-20) The organizations schema has references (UUID) to an interface records, as opposed to storing the interface data directly in the organization record.
Updating sample data to create interfaces and using their ids for organizations.
Some of the organizations do not have interfaces at all now (those which did not have any meaningful info).
- Are the JIRAs under active …
=> MODORGS-20 interface references

ramls/address.raml, ramls/category.raml, ramls/contact.raml, ramls/email.raml, ramls/interface.raml, ramls/organization.raml, ramls/phone_number.raml, ramls/url.raml, src/main/java/org/folio/rest/impl/AddressesAPI.java, src/main/java/org/folio/rest/impl/CategoriesAPI.java, src/main/java/org/folio/rest/impl/ContactsAPI.java, src/main/java/org/folio/rest/impl/EmailsAPI.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/rest/impl/PhoneNumbersAPI.java, src/main/java/org/folio/rest/impl/UrlsAPI.java
[MODORGS-13](https://issues.folio.org/browse/MODORGS-13) Add the validate trait to endpoints in all RAML files.
- specified validation trait for all endpoints across all RAML files
- applied @Validation to get collection methods
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> MODORGS-13 add validate trait to raml

src/main/resources/data/interfaces/bibsam_interface.json, src/main/resources/data/interfaces/mln_interface.json, src/main/resources/data/interfaces/rsc_interface.json, src/main/resources/data/organizations/bibsam.json, src/main/resources/data/organizations/mln.json, src/main/resources/data/organizations/rsc.json, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORGS-23](https://issues.folio.org/browse/MODORGS-23) Sample data: add non-vendor organizations
- added 3 new non-vendor organization
- added 3 interfaces for new organizations
- updated `initialQuantity` for organization, interface enities
=> MODORGS-23 Sample data: add non-vendor organizations

src/main/resources/data/organizations/acso.json, src/main/resources/data/organizations/alexs.json, src/main/resources/data/organizations/amaz.json, src/main/resources/data/organizations/gobi.json, src/main/resources/data/organizations/harra.json, src/main/resources/data/organizations/mgnp.json, src/main/resources/data/organizations/naxo.json, src/main/resources/data/organizations/sjean.json, src/main/resources/data/organizations/srebsco.json, src/main/resources/data/organizations/tafg.json, src/main/resources/data/organizations/usgs.json, src/main/resources/data/organizations/zroco.json, src/main/resources/data/organizations/zsusan.json
While working on switching mod-gobi to use mod-orgs dependency, I observed that the categories in the sample data are actual values instead of UUIDs of categories, as a result they are not showing up on the UI as well. Modifying it to use correct UUIDs
add category UUID values to all organization sample data
Ideally all of the PRs involved in breaking …
=> Fixing categories values

NEWS.md, pom.xml
[MODORGS-24](https://issues.folio.org/browse/MODORGS-24) Release 1.0.0
=> MODORGS-24 - Release 1.0.0

src/main/resources/data/contacts/acso_contact.json, src/main/resources/data/contacts/alexs_contact.json, src/main/resources/data/contacts/amaz_contact.json, src/main/resources/data/contacts/gobi_contact.json, src/main/resources/data/contacts/harra_contact.json, src/main/resources/data/contacts/mgnp_contact.json, src/main/resources/data/contacts/naxo_contact.json, src/main/resources/data/contacts/sjean_contact.json, src/main/resources/data/contacts/srebsco_contact.json, src/main/resources/data/contacts/tafg_contact.json, src/main/resources/data/contacts/usgs_contact.json, src/main/resources/data/contacts/zroco_contact.json, src/main/resources/data/contacts/zsusan_contact.json, src/test/resources/contact.sample
https://issues.folio.org/browse/MODORGS-27 - Add default inactive value
added the field inactive with default value to all the sample data files
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> MODORGS-27-adding default inactive value

src/main/resources/data/interfaces/acso_interface.json, src/main/resources/data/interfaces/amaz_interface.json, src/main/resources/data/interfaces/bibsam_interface.json, src/main/resources/data/interfaces/gobi_interface.json, src/main/resources/data/interfaces/harra_interface.json, src/main/resources/data/interfaces/mln_interface.json, src/main/resources/data/interfaces/naxo_interface.json, src/main/resources/data/interfaces/rsc_interface.json, src/main/resources/data/interfaces/srebsco_interface.json, src/test/resources/interface.sample
[MODORGS-28](https://issues.folio.org/browse/MODORGS-28) Add field `type` to interface.json schema
- updating ramls/acq-models
- updating sample data
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> MODORGS-28 Interface schema update: new field - type

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/contact.raml, ramls/interface.raml
[MODORGS-30](https://issues.folio.org/browse/MODORGS-30) Create MODORGS release
- The News file includes completed stories for [1.1.0 version](https://issues.folio.org/projects/MODORGS/versions/11624)
- The release version will be `1.1.0`. The new property was introduced however it is optional and might be considered as not braking change
- Module interfaces and ramls versions updated to 1.1: `organizations-storage.contacts` and `organizations-storage.interfaces`
- News updated with release details
- What other modules will …
=> MODORGS-30 Create MODORGS release

src/test/resources/phoneNumber.sample
Pointing to the latest acq-model with changes to phone number type
=> MODORGS-29- Phone Number Type change

src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java
[MODORGS-32](https://issues.folio.org/browse/MODORGS-32)
Include metadata property in JSON schemas
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> MODORGS-32 include metadata property in json schemas

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/address.raml, ramls/category.raml, ramls/contact.raml, ramls/email.raml, ramls/interface.raml, ramls/organization.raml, ramls/phone_number.raml, ramls/url.raml, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORGS-34 Create MODORGS release
* Interface versions updated
* News.md file updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MODORGS-34 Create release 2.0.0

pom.xml
API tests are failing because the metadata schema cannot be verified. 
Include the raml-utils/* path in the jsonschemas path, so that it can be picked up by the /_/jsonSchemas API
https://github.com/folio-org/raml-module-builder#json-schemas-api
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> Adding raml-util to jsonschema paths

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/organization.raml
[MODORGS-39](https://issues.folio.org/browse/MODORGS-39) - Release 2.1.0
- Updating News.md
- Changing `organizations-storage.organizations` interface and raml versions from `2.0` to `2.1`
=> MODORGS-39 - Release 2.1.0

src/main/resources/data/organizations/acso.json, src/main/resources/data/organizations/amaz.json, src/main/resources/data/organizations/mgnp.json, src/main/resources/data/organizations/naxo.json, src/main/resources/data/organizations/tafg.json
fix sample data for Organizations app
https://issues.folio.org/browse/UIORGS-106
While …
=> UIOR-106 fix sample data

pom.xml, src/main/java/org/folio/rest/impl/AddressesAPI.java, src/main/java/org/folio/rest/impl/CategoriesAPI.java, src/main/java/org/folio/rest/impl/ContactsAPI.java, src/main/java/org/folio/rest/impl/EmailsAPI.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/rest/impl/PhoneNumbersAPI.java, src/main/java/org/folio/rest/impl/UrlsAPI.java
[MODORGS-52](https://issues.folio.org/browse/MODORGS-52) - Update RMB to 28.1.1
Updating to RMB version
Updating to RMB 28.1.1
Removing unused imports
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> MODORGS-52 - Update RMB to 28.1.1

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/organization.raml
=> MODORGS-57 - Release 2.2.1

descriptors/ModuleDescriptor-template.json, src/main/resources/templates/db_scripts/migration/organizations.sql, src/main/resources/templates/db_scripts/schema.json
[MODORGS-53](https://issues.folio.org/browse/MODORGS-53) - Organization code optional in back-end, required in front-end
In the front-end the organization code is required, but non-required in back-end.
Organization schema changing - code becomes required. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> MODORGS-53 - Organization code optional in back-end, required in front-end

pom.xml, src/main/resources/templates/db_scripts/migration/organizations.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORGS-60
* added migration script for organizations.code
* moved unique index creation from schema.json to script
* bumped up dependency versions in pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MODORGS-60 Migration script for organizations code

NEWS.md, pom.xml, ramls/organization.raml
=> MODORGS-62 - Release 3.0.0

src/main/java/org/folio/persist/CriterionBuilder.java, src/main/java/org/folio/persist/Tx.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/service/InterfaceService.java, src/main/java/org/folio/util/ResponseUtils.java, src/test/java/org/folio/rest/impl/InterfaceCredentialsTest.java
- Add cascade deletion of credential once we delete interface by id
While it's helpful …
=> [MODORGS-58] Fix unable to delete Interface in Organizations app

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
[MODORGS-63](https://issues.folio.org/browse/MODORGS-63)  - Bugfix Release 3.0.1
=> [MODORGS-63] - Bugfix Release 3.0.1

src/main/resources/templates/db_scripts/migration/add_default_is_vendor_value.sql, src/main/resources/templates/db_scripts/migration/make_organization_code_unique.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
[MODORGSTOR-68](https://issues.folio.org/browse/MODORGSTOR-68)
- drop unique index to update it upon migration from 3.0.0, 3.0.1 to 3.0.2
- fixed definition of unique index on organization.code to make index case sensitive
- moved migration scripts to scripts section
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
=> MODORGSTOR-68 Migration issue between Edelweiss and Fameflower

pom.xml, src/main/java/org/folio/persist/CriterionBuilder.java, src/main/java/org/folio/persist/Tx.java, src/main/java/org/folio/rest/impl/AddressesAPI.java, src/main/java/org/folio/rest/impl/CategoriesAPI.java, src/main/java/org/folio/rest/impl/ContactsAPI.java, src/main/java/org/folio/rest/impl/EmailsAPI.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/service/InterfaceService.java, src/main/java/org/folio/util/ResponseUtils.java, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/InterfaceCredentialsTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/impl/TestBase.java
* https://issues.folio.org/browse/MODORGSTOR-72
* migrated to RMB 30.0.0
* migrated to JUnit 5
* code reformat, optimized imports
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> MODORGSTOR-72 Update to RMB v30

descriptors/ModuleDescriptor-template.json
See https://issues.folio.org/browse/MODORGSTOR-69 Securing APIs by default
=> Securing APIs by default

descriptors/ModuleDescriptor-template.json, ramls/organization.raml
https://issues.folio.org/browse/MODORGSTOR-73
* increased interface version
While it's …
=> MODORGSTOR-73 interface version updated

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-71
While it's helpful …
=> MODORGSTOR-71 release 3.1.0

pom.xml
* https://issues.folio.org/browse/MODORGSTOR-72
* migrated to RMB 30.2.4
While it's …
=> [MODORGSTOR-75]- mod-organizations-storage: Update to RMB 30.2.4

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-76
While it's helpful …
=> [MODORGSTOR-76] - Bugfix release 3.1.1

NEWS.md, pom.xml
Merge bugfix to master
While it's helpful for reviewers to help identify potential …
=> Tmp 3.1.1 to master

src/main/resources/data/organizations/acso.json, src/main/resources/data/organizations/amaz.json, src/main/resources/data/organizations/gobi.json, src/main/resources/data/organizations/mgnp.json, src/main/resources/data/organizations/naxo.json, src/main/resources/data/organizations/sjean.json, src/main/resources/data/organizations/tafg.json, src/main/resources/data/organizations/zroco.json, src/main/resources/templates/db_scripts/migration/make_organization_export_to_accounting_default.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/StorageTestSuite.java
https://issues.folio.org/browse/MODORGSTOR-77
* added exportToAccounting field
* added migration script
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> MODORGSTOR-77 added exportToAccounting field

pom.xml, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORGSTOR-85
* configured exactCount parameter
While …
=> MODORGSTOR-85 increased totalRecords precision up to 20000 records in total

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
[MODORGSTOR-81](https://issues.folio.org/browse/MODORGSTOR-81)
MODORGSTOR (mod-organizations-storage) release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> Tmp release 3.2.0

pom.xml
https://issues.folio.org/browse/MODORGSTOR-91
* fixed logging
* rmb v31.1.4
While it's …
=> MODORGSTOR-91 fixed logging

pom.xml
https://issues.folio.org/browse/MODORGSTOR-93
* rmb 31.1.5
While it's helpful for …
=> MODORGSTOR-93 rmb 31.1.5

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-92
* update release notes 
While it's helpful …
=> MODORGSTOR-92 release 3.2.1

NEWS.md
release 3.2.1 news.md -> master branch
=> MODORGSTOR-92 release 3.2.1 news.md -> master branch

NEWS.md, pom.xml
Bugfix release 3.2.2
1. RMB version changed
2. Logging settings changed
While it's …
=> Tmp bugfix 3.2.2

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/persist/CriterionBuilder.java, src/main/java/org/folio/persist/Tx.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/service/InterfaceService.java, src/main/java/org/folio/util/ResponseUtils.java, src/main/resources/log4j2.properties, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/InterfaceCredentialsTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java, src/test/resources/log4j2.properties
https://issues.folio.org/browse/MODORGSTOR-98
* rmb updated
While it's helpful for …
=> MODORGSTOR-98 update rmb 32.1.0

NEWS.md, pom.xml
[MODORGSTOR-97](https://issues.folio.org/browse/MODORGSTOR-97)
While it's helpful for …
=> MODORGSTOR-97 Release 4.0.0

PERSONAL_DATA_DISCLOSURE.md
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> [MODORGSTOR-100] - Add personal data disclosure form

pom.xml, src/main/java/org/folio/service/InterfaceService.java, src/main/java/org/folio/util/ResponseUtils.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java
* https://issues.folio.org/browse/MODORGSTOR-104
* updated rmb dependency to v33.0.0
* migrated embedded database to test containers
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> MODORGSTOR-104 bump rmb up to 33.0.0

NEWS.md, pom.xml
MODORGSTOR (mod-organizations-storage) release > https://issues.folio.org/browse/MODORGSTOR-103
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> [MODORGSTOR-103] Update NEWS.md.

pom.xml
https://issues.folio.org/browse/MODORGSTOR-117 …
=> MODORGSTOR-117. Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
KIWI Bugfix 4.1.1
While it's helpful for reviewers to help identify potential problems, …
=> [MODORGSTOR-120] - KIWI Bugfix 4.1.1

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-123
While it's …
=> MODORGSTOR-123 Lotus 2022 R1 module release

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/organization_type.raml, src/main/java/org/folio/rest/impl/OrganizationTypesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/organization_types/auction_house.json, src/main/resources/data/organization_types/book_trade.json, src/main/resources/data/organization_types/private_person.json, src/main/resources/data/organization_types/publisher.json, src/main/resources/templates/db_scripts/organization_type_check_reference_triggers.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrganizationTypesTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/utils/TestEntities.java, src/test/resources/organization_type.sample
[UXPROD-2553](https://issues.folio.org/browse/UXPROD-2553)
[MODORGSTOR-121](https://issues.folio.org/browse/MODORGSTOR-121)
Intended for Morning Glory release.
- Modules depending on `acq-models` and using the `organizations-storage.organizations` interface will be affected by this change. So far following modules have been identified, that need to update acq-models:
* [mod-organizations](https://github.com/folio-org/mod-organizations) - [PR …
=> [MODORGSTOR-121] - Add organization types API

pom.xml
https://issues.folio.org/browse/MODORGSTOR-129
* updated rmb to  v34.1.0
While it's …
=> MODORGSTOR-129 rmb v34.1.0

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-127
While it's …
=> MODORGSTOR-127 Morning Glory R2 2022 v4.3.0 release notes

pom.xml, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java
* https://issues.folio.org/browse/MODORGSTOR-131
* RMB v35.0.1 upgrade
While it's …
=> MODORGSTOR-131 RMB v35.0.1 upgrade

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORGSTOR-132
While it's …
=> MODORGSTOR-132 release notes v4.4.0 (Nolana R3)

pom.xml
https://issues.folio.org/browse/MODORGSTOR-132
* fix new snapshow version
While it's …
=> MODORGSTOR-132 fix snapshot version

PULL_REQUEST_TEMPLATE.md, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/service/InterfaceService.java, src/main/java/org/folio/util/ResponseUtils.java, src/main/resources/log4j2-json.properties
https://issues.folio.org/browse/MODORGSTOR-122
Logging has been improved for more productive troubleshooting
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> [MODORGSTOR-122] - Logging improvement

NEWS.md, pom.xml
While it's helpful for reviewers to help identify potential problems,
ensuring that it's safe …
=> [MODORGSTOR-139] - Release 4.5.0

ramls/address.raml, ramls/category.raml, ramls/contact.raml, ramls/email.raml, ramls/interface.raml, ramls/organization.raml, ramls/organization_type.raml, ramls/phone_number.raml, ramls/url.raml, src/main/java/org/folio/rest/impl/AddressesAPI.java, src/main/java/org/folio/rest/impl/CategoriesAPI.java, src/main/java/org/folio/rest/impl/ContactsAPI.java, src/main/java/org/folio/rest/impl/EmailsAPI.java, src/main/java/org/folio/rest/impl/InterfacesAPI.java, src/main/java/org/folio/rest/impl/OrganizationTypesAPI.java, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/rest/impl/PhoneNumbersAPI.java, src/main/java/org/folio/rest/impl/UrlsAPI.java
Resolves: [MODORGSTOR-137](https://issues.folio.org/browse/MODORGSTOR-137) Update dependent raml-util
especially as the number of inter-module and inter-team dependencies …
=> [MODORGSTOR-137] Update dependent raml-util

Dockerfile, Jenkinsfile, pom.xml
https://issues.folio.org/browse/MODORGSTOR-143 …
=> [MODORGSTOR-143]-java 17 upgrade.

NEWS.md, pom.xml
[MODORGSTOR-151](https://issues.folio.org/browse/MODORGSTOR-151) - mod-organizations-storage: module release
especially as the number of inter-module and inter-team …
=> [MODORGSTOR-151] - Release v4.6.0

descriptors/ModuleDescriptor-template.json, ramls/banking_accoun_type.raml, ramls/organization_type.raml, src/main/java/org/folio/rest/impl/BankingAccountTypesAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/BankingAccountTypesTest.java, src/test/java/org/folio/rest/impl/OrganizationTypesTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/resources/banking_account_type.sample
https://issues.folio.org/browse/MODORGSTOR-148 …
=> [MODORGSTOR-148] - BE - Implement CRUD for Banking Account Types

descriptors/ModuleDescriptor-template.json, ramls/banking_accoun_type.raml, ramls/setting.raml, src/main/java/org/folio/rest/impl/OrganizationSettingsAPI.java, src/main/resources/templates/db_scripts/migration/create_banking_information_setting.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrganizationSettingsTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java
https://issues.folio.org/browse/MODORG-53
Created corresponding table and API
While it's …
=> [MODORG-53] - BE - Implement CRUD for Organization Settings

descriptors/ModuleDescriptor-template.json, ramls/banking_information.raml, src/main/java/org/folio/rest/impl/BankingInformationAPI.java, src/main/resources/templates/db_scripts/migration/create_banking_information_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/BankingInformationTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java
[MODORG-54](https://issues.folio.org/browse/MODORG-54) - Banking information fields edit and delete
especially as the number of inter-module and inter-team dependencies …
=> [MODORG-54] - Banking information fields edit and delete

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORGSTOR-148 - Add unique index on name field
While it's …
=> [MODORGSTOR-148] - Add unique index on name

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORG-60
Added regular index for bankAccountNumber
```
16:30:28 [407436/organizations;604230/organizations-storage] [diku] [cc535e94-3310-5a7c-a767-08c30c6583fd] [mod_organizations_storage] INFO  RestRouting          invoking getOrganizationsStorageBankingInformation
16:30:28 [407436/organizations;604230/organizations-storage] [diku] [cc535e94-3310-5a7c-a767-08c30c6583fd] [mod_organizations_storage] INFO  CQL2PgJSON           loadDbSchema: Loaded templates/db_scripts/schema.json OK
16:30:28 [407436/organizations;604230/organizations-storage] [diku] [cc535e94-3310-5a7c-a767-08c30c6583fd] [mod_organizations_storage] INFO  CQL2PgJSON           index banking_information.jsonb->>'bankAccountNumber' generated SQL CASE WHEN length(lower(f_unaccent('222222'))) <= …
```
=> [MODORG-60] - Added index for bankAccountNumber

pom.xml
https://issues.folio.org/browse/MODORGSTOR-149 …
=> [MODORGSTOR-149] - Update RMB and vertx to the latest version

pom.xml
https://folio-org.atlassian.net/browse/MODORGSTOR-156
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
=> [MODORGSTOR-156] Upgrade RAML Module Builder

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODORGSTOR-158
=> [MODORGSTOR-158] - Release v4.7.0

pom.xml
https://folio-org.atlassian.net/browse/MODORGSTOR-158
Update pom
While it's helpful for …
=> prepare for next development iteration

src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODORGSTOR-163
UI able to handle error thrown after adding foreign key
=> MODORGSTOR-163. Banking - prevent deletion of account type if it is being used by an organization

pom.xml, src/test/java/org/folio/rest/impl/StorageTestSuite.java
[[MODORGSTOR-166] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODORGSTOR-166)
- Update versions
- Add module descriptor validator
=> [MODORGSTOR-166] Update libraries of dependant acq modules to the latest versions

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102 …
=> [FOLIO-4102] - Release v4.8.0

src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/service/OrganizationService.java, src/test/java/org/folio/rest/impl/BankingInformationTest.java, src/test/resources/organization2.sample
https://folio-org.atlassian.net/browse/MODORGSTOR-172
Delete associated banking information in scope of the same transaction. Used InterfaceService as a reference.
=> MODORGSTOR-172. Error message when an organization cannot be deleted because of banking information

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/OrganizationsAPI.java, src/main/java/org/folio/service/OrganizationService.java, src/test/java/org/folio/rest/impl/BankingInformationTest.java, src/test/resources/organization2.sample
Make Ramsons 4.8.1 Bug Fix release with including fix 
https://folio-org.atlassian.net/browse/MODORGSTOR-172 Error message when an organization cannot be deleted because of banking information
=> [MODORGSTOR-172] Ramsons Bug Fix release 4.8.1

Dockerfile, Jenkinsfile, pom.xml
[[FOLIO-4200] Update to mod-organizations-storage Java 21](https://folio-org.atlassian.net/browse/FOLIO-4200)
Update java and dependency versions
=> [FOLIO-4200] Update to mod-organizations-storage Java 21

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODORGSTOR-176 …
=> Release v4.9.0

.github/dependabot.yml, CODEOWNERS, PULL_REQUEST_TEMPLATE.md
https://folio-org.atlassian.net/browse/MODORGSTOR-179
- Setup dependant bot
- Add codeowners
- Simplify PR_TEMPLATE
=> MODORGSTOR-179. Setup dependabot for your module

src/main/resources/data/organizations-3.2.0/sjean.json
Need to make at least one organization as donor organization
https://folio-org.atlassian.net/browse/MODFISTO-527
_Provide a brief technical summary of the changes._
---
=> MODFISTO-527. Update after QA review

src/main/resources/data/organizations-5.0.0/cac.json, src/main/resources/data/organizations-5.0.0/gld.json
- <https://folio-org.atlassian.net/browse/MODORG-84>
- Simplify currencies for 2 vendors to improve QA testing experience when working with new vendors
=> [MODORG-84-3]. Simplify currencies for 2 vendors

src/main/resources/templates/db_scripts/migration/2025_07_23_populate_orders_jobs_missing_fields.ftl, src/main/resources/templates/db_scripts/migration/2025_07_23_populate_orders_jobs_missing_fields.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrganizationTypesTest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/resources/schemas/configuration_schema.sql
[[MODORGSTOR-181] Migration script for organization integration type not executing properly (Ramsons to Sunflower)](https://folio-org.atlassian.net/browse/MODORGSTOR-181)
- Populate integrationType, transmissionMethod and fileFormat for EDIFACT_ORDERS_EXPORT type configs if missing in mod-configuration
=> [MODORGSTOR-181] Migration script for organization integration type not executing properly (Ramsons to Sunflower)
